const ERROR_BAD_REQUEST = 400;
const ERROR_UNAUTHORIZED = 401;
const ERROR_FORBIDDEN = 403;
const ERROR_NOT_FOUND = 404;
const STATUS_CREATED = 201;

module.exports = {
  ERROR_BAD_REQUEST,
  ERROR_FORBIDDEN,
  ERROR_UNAUTHORIZED,
  ERROR_NOT_FOUND,
  STATUS_CREATED,
};

// const ERROR_BAD_REQUEST = 400;
// const ERROR_UNAUTHORIZED = 401;
// const ERROR_FORBIDDEN = 403;
// const ERROR_NOT_FOUND = 404;
// const ERROR_INTERNAL_SERVER = 500;
// const STATUS_CREATED = 201;
// const STATUS_OK = 200;

// module.exports = {
//   ERROR_BAD_REQUEST,
//   ERROR_FORBIDDEN,
//   ERROR_UNAUTHORIZED,
//   ERROR_NOT_FOUND,
//   ERROR_INTERNAL_SERVER,
//   STATUS_CREATED,
//   STATUS_OK,
// };
